version: "3.9"
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_DIALECT: ${DB_DIALECT}
      DB_PORT: ${DB_PORT}
      EMAIL: ${EMAIL}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      ALTER: ${ALTER}
    depends_on:
      - redis
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mysql_data:
